/*
 * generated by Xtext
 */
package org.apache.pigeditor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.apache.pigeditor.ui.internal.PigActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.apache.pigeditor.ui.internal.PigActivator.getInstance().getInjector("org.apache.pigeditor.Pig");
	}
	
}
