/*
* generated by Xtext
*/
package org.apache.pigeditor.ui.contentassist;

import org.apache.pigeditor.ui.contentassist.AbstractPigProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PigProposalProvider extends AbstractPigProposalProvider {

}
