/*
* generated by Xtext
*/
package org.apache.pigeditor.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.apache.pigeditor.services.PigGrammarAccess;

public class PigParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PigGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.apache.pigeditor.parser.antlr.internal.InternalPigParser createParser(XtextTokenStream stream) {
		return new org.apache.pigeditor.parser.antlr.internal.InternalPigParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Query";
	}
	
	public PigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
