/*
* generated by Xtext
*/
package org.apache.pigeditor.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PigOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
