/*
 * generated by Xtext
 */
package org.apache.pigeditor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PigRuntimeModule extends org.apache.pigeditor.AbstractPigRuntimeModule {

}
