/*
 * generated by Xtext
 */
package org.apache.pigeditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PigUiModule extends org.apache.pigeditor.ui.AbstractPigUiModule {
	public PigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
